### PR TITLE
Fix Safari icons

### LINKED ISSUE #3: Custom icons on mobile (iOS)
Great plugin - thank you!

I am using the [provided css ](https://github.com/replete/obsidian-tasks-custom-icons/blob/main/TasksMonoEmojis-lucide2/TasksMonoEmojis-lucide2.css) and it is working great on desktop (PC and Mac), but not on mobile. 

Any ideas?

Thanks!

### PR DESCRIPTION
**Pull request by replete**
~~Turns out iOS Obsidian was actually displaying the font fine using the `U+1234` `unicode-range` syntax.~~
~~The previous 'fix' that we rolled back in the end, was due to a red herring leading to my belief that this wasn't working on iOS. I didn't have an iPhone to test on and assumed that if the demo page worked in iOS Safari Desktop, it would work the same in iOS Obsidian as its the same engine – but it does not, and to make the demo page work we've had to use the u1234 not the U+1234 format. No idea.~~

~~The good news is I've tested it on real hardware (acquired an old iPhone 7 for testing recently) and it works fine.~~

UPDATE: Actually there is some kind of regression bug in some version after 15 of Safari, see comments in thread. 

## Main change

Using `@supports`, we are selectively serving an SVG font to Safari iOS and using the `u1234` unicode-range format to fix font display on modern iOS. Other browsers are served `woff2` using `U+1234` unicode-range format, as used previously. For an example view the source of `TasksMonoEmojis-lucide2.html` to see the changes around the `@font-face` declaration.

## Other Changes
While I was there I made some improvements:
1. Installed Dataview plugin into repo, to test the fields (common enough usecase I guess)
Screenshot 2024-09-04 at 02 22 05

2. Renamed test vault tasks for clarity
Screenshot 2024-09-04 at 00 01 17

3. Tidied up script to make it more maintainable
4. Improved demo HTML pages
Screenshot 2024-09-04 at 02 23 02

5. Updated URL in script to match new repo URL
6. Add new function to script to copy all snippets to _vault on build
7. Improved script logging, making it more clear
Screenshot 2024-09-04 at 02 23 32

8. Added note on iOS weirdness to script around demo HTML
9. Updated code sample in README
10. Bumped version to 1.0.6

## Devices

Windows 11:
Screenshot 2024-09-04 at 02 32 00

MacOS 14:
Screenshot 2024-09-04 at 02 33 04

Android 13:
image

iPhone 7+
Screenshot 2024-09-04 at 02 21 40

Resolves #3

### CODE REVIEW

**Comment by GGlider** [comment]
Really appreciating this @replete !

**Comment by claremacrae** [comment]
This is isn’t forgotten. I’m hoping to be able to review and merge this coming week.

**Comment by replete** [comment]
Hi Clare, I've had a user report that this isn't working in modern iOS.

According to [this forum post](https://forums.macrumors.com/threads/major-text-rendering-bug-in-macos-safari-17-0.2406391/) it appears in fact there is a some kind of regression bug in Safari.


> "The problem in Safari seems to be the usage of .woff or .ttf fonts in combination with "unicode-range". If I delete "unicode-range", the problem goes away. Also, if I only use the .svg font, no problem"

Based on this, I will modify this PR to generate SVG type fonts and we can see if it resolves the problem. Frontend is fun.

**Comment by replete** [comment]
I've pushed code that renders an SVG version targeted just to Safari on iOS.
It also includes the same for Safari Desktop so that the demo page works as expected.

Screenshot 2024-09-15 at 23 51 15

This needs to be tested in Obsidian on iOS 17+. I cannot load non-dev apps into my iOS emulator so I am unable to test this. @lup3v0 Would you mind trying the new version and let me know your iOS version please.

Safari really is the new IE.

**Comment by lup3v0** [comment]
Did the following:

- Grabbed css snippet from [here](https://github.com/obsidian-tasks-group/obsidian-tasks-custom-icons/blob/205154f5f346fa265691b3e914c6025dab8c37a7/TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css)
- Synced in to iPhone ( iOS 17.6.1)
- Activated the new css snippet
- Restarted Obsidian

This is how tasks get rendered:
Task SVG

Am I going about this the right way?

FYI: Using Tasks Version 7.10.0

**Comment by replete** [comment]
Thanks for the feedback, I have another version to try. I've noticed this behaviour before

**Comment by replete** [comment]
@lup3v0 I've pushed another version of the snippet, any should work for testing but here's lucide2 raw link for convenience:
https://raw.githubusercontent.com/obsidian-tasks-group/obsidian-tasks-custom-icons/e73d1d799d189637cb5077aeb36052b37aa1e917/_vault/.obsidian/snippets/TasksMonoEmojis-lucide2.css

Hopefully this works 🤞

**Comment by claremacrae** [comment]
I am very grateful that you are both working on this - thank you!

**Comment by lup3v0** [comment]
Happy to help Clare - I **love** the task plugin and your work is incredible!

@replete: Unfortunately that didn't work either. Only the default emojis are showing, no replacement. Coincidentally, iOS 18 was released today, and I was hoping this meant some bug fixes for Safari. I upgraded and tried both your latest css as well as the original but sadly without success.

Do I need to change the Tasks plugin version for this test?

Hope you are not running out of ideas yet...

**Comment by replete** [comment]
I have an Intel Mac and my backup iPhone only runs iOS 15. So I decided to just buy an old iPhone SE 2020. I'll be able to test on real hardware next week and solve the problem.

**Comment by claremacrae** [comment]
Wow. Thank you Phil.

**Comment by replete** [comment]
Screenshot 2024-09-21 at 14 29 05

My iPhone arrived this morning so I figured out a solution and pushed the fix.

The solution after exploring all other options (including multiple font-face definitions, codepoint sorting, hex padding, wildcard codepoint symbols different font formats, range+1, and a mixture of these) was to use a very wide unicode range rather than individual codepoints to make this work in Obsidian iOS' safari webview.

The compromise means that user-entered emojis in task items might display not display on iOS.

I've also updated screenshots in README and tidied up slightly.

**Comment by replete** [comment]
Works for me on iOS 18 too

**Comment by lup3v0** [comment]
It's working! What an effort... Thank you for the tenacity!

For consistency, I added the following to the snippet:
- Replace emojis for the auto-suggester
- Replace emojis for the modal window

Perhaps this is useful for someone else out there!

```css

/* ----------------------------------------------------------------
REPLACE AUTO-SUGGEST EMOJIS
-----------------------------------------------------------------*/
	.suggestion{
    	font-family: 'TasksMonoEmojis', var(--font-text);
	}
/* ----------------------------------------------------------------
REPLACE TASK MODAL EMOJIS
-----------------------------------------------------------------*/
	/* Priority icons */
	.tasks-modal-priority-section {
	font-family: 'TasksMonoEmojis', var(--font-text);
	}
	/* Date icons */
	.tasks-modal-parsed-date{
	font-family: 'TasksMonoEmojis', var(--font-text);
	}
```

**Comment by replete** [comment]
Thanks for testing, @lup3v0 good to hear it works.

I can add the other selectors to the PR but that `.suggestion` css class looks like it could conflict with another plugin using the same class and there should probably be another class in front of it. I can't seem to get autosuggest to work so could you advise. I'm guessing something like `.cm-line:has(.task-list-label) .suggestion`?

**Comment by lup3v0** [comment]
Good point.

Looks like the parent has ```.suggestion-container```
So could do:
```css
span.tasks-list-text,
.cm-line:has(.task-list-label) [class^=cm-list-],
span.task-extras,
.tasks-postpone,
.tasks-backlink,
.tasks-edit::after,
.suggestion-container .suggestion,
.tasks-modal-priority-section,
.tasks-modal-parsed-date {
	font-family: 'TasksMonoEmojis', var(--font-text);
}
```
Would that do?

**Comment by GGlider** [comment]
Yes, thank you so much for your effort and tenacity.
I tested it as well and it works on the desktop perfectly, on the iPhone Obsidian app not so much.
Am I missing something? See the attached screenshots.

shot1

shot2

**Comment by replete** [comment]
@GGlider What version of iOS do you have?

**Comment by claremacrae** [comment]
@GGlider Just as a precaution can you confirm the snippet is enabled on iPhone?

**Comment by replete** [comment]
@GGlider Besides letting me know your iOS version, you could confirm that the file is definitely loaded by modifying this in the CSS snippet:

from
```
.suggestion-container .suggestion {
	font-family: 'TasksMonoEmojis', var(--font-text);
}
```
to:
```
.suggestion-container .suggestion {
	font-family: 'TasksMonoEmojis', var(--font-text);
        outline: 1px solid red;
}
```
If this has loaded correctly, task-related elements should be surrounded with a red box.

**Comment by GGlider** [comment]
> @GGlider What version of iOS do you have?

- Newest, iOS 18.0
- Hadn't, just downloaded the code as is currently on Git
- Changed it now - No change, still the color icons
shot3


> @GGlider Just as a precaution can you confirm the snippet is enabled on iPhone?
- Yes, it's enabled in the the appearance settings
shot4

- Also updated the Tasks Plugin  to 7.10.0 before implementing the CSS

**Comment by replete** [comment]
@GGlider Is the Obsidian app definitely up to date?

If you aren't seeing something like this after adding: `outline: 1px solid red;`, the CSS has not been updated:
Screenshot 2024-09-24 at 22 04 29 jpeg

You can copy folders onto iPhone via USB. On mac it looks like this:
Phil’s iPhone 2024-09-24 22-10-12



Screenshot 2024-09-24 at 22 02 36

**Comment by replete** [comment]
@GGlider Aha, I've just realized that the CSS in your screenshot is not the up to date CSS from this PR, that will be broken.

This is a link to the update (v1.0.6) file from this PR:
https://github.com/obsidian-tasks-group/obsidian-tasks-custom-icons/blob/8f7d91b5fcff946c722718be2b28fc45c634ad58/TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css

That should be the CSS file you are testing, not the one from the main repo. It hasn't been merged yet.

**Comment by claremacrae** [comment]
I'm back online now... so assuming @GGlider comes back and confirms the changes from this PR work, I will go ahead and approve and merge this!

**Comment by replete** [comment]
@GGlider Can you try the updated CSS please?
https://github.com/obsidian-tasks-group/obsidian-tasks-custom-icons/blob/8f7d91b5fcff946c722718be2b28fc45c634ad58/TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css

Would like to get this merged soon. Thanks for checking for us.

**Comment by GGlider** [comment]
@replete Sry, I was in transit.
Just exchanged it and it works like a charm, both on iOS and macOS!

🚀

**Comment by replete** [comment]
@GGlider Good to hear it works as expected. The others will work the same as they are generated in the same way, my testing was done with lucide2. The other two icon packs are actually incomplete and not very useful, there only for reference.

Thanks for testing. Cheers

**Comment by GGlider** [comment]
@replete Ok. Was shortly testing the lucide2 as well, woring on macOS, but not on iOS (but I think the code is not updated yet, it says it was updated 3 weeks ago).
Let me know if I can help you with testing.

At this point, thank you again for all your effort, really appreciate this!

**Comment by replete** [comment]
@GGlider That's the code v1.0.5 from the main repo. 
Code in this Pull Request has not yet been merged into the main repo branch yet. 
This is how pull requests work on github, we make a pull request and make new changes here and when its tested merge that into the main repository branch.

You can optionally test lucide2 from this URL:
https://github.com/obsidian-tasks-group/obsidian-tasks-custom-icons/blob/8f7d91b5fcff946c722718be2b28fc45c634ad58/TasksMonoEmojis-lucide2/TasksMonoEmojis-lucide2.css

It will work just the same as the one you just tested. Phil

**Comment by mameesie** [comment]
Works for me as well on IOS 18, thanks for this!

**Comment by replete** [comment]
I think this is ready for merging, @GGlider's issues were from testing the wrong (v1.0.5) files from the main branch instead of this PR.

**Comment by claremacrae** [comment]
Awesome work. Thank you to everyone for the contributions and testing!

**Pull request merged**
