### PR TITLE
Fix for the 'Files glob patterns' bug.

### PR DESCRIPTION
**Pull request by ArthurFGrillo**

### CODE REVIEW

**Comment by claremacrae** [comment]
Hi @ArthurFGrillo 

Many thanks for taking the time to make the PR!

What is the problem that this is fixing please? How would we recreate the problem with the old code, so that we can then test the fix?

Thanks again - it’s much appreciated.

**Comment by replete** [comment]
I'm not sure this fixes anything, it changes an absolute path to a relative one.

I've tested this on Windows in Node 18, just in case there was a problem with Windows path resolution but it works as expected.

@ArthurFGrillo Can you describe your environment and what problem was solved by this?

**Comment by ArthurFGrillo** [comment]
I am using Node 18.14.2 on Windows 11.

I was trying to make a new icon pack for myself, but every time I ran `npm run build` I would get the following error:
```
> obsidian-tasks-custom-icons@1.0.3 build
> node ./index.js

C:\Development\ReactApps\obsidian-tasks-custom-icons\node_modules\webfont\dist\index.js:401
                    throw new Error("Files glob patterns specified did not match any files");
                          ^

Error: Files glob patterns specified did not match any files
    at C:\Development\ReactApps\obsidian-tasks-custom-icons\node_modules\webfont\dist\index.js:401:27
    at step (C:\Development\ReactApps\obsidian-tasks-custom-icons\node_modules\webfont\dist\index.js:96:23)
    at Object.next (C:\Development\ReactApps\obsidian-tasks-custom-icons\node_modules\webfont\dist\index.js:77:53)
    at fulfilled (C:\Development\ReactApps\obsidian-tasks-custom-icons\node_modules\webfont\dist\index.js:67:58)

Node.js v18.14.2
```

After some debugging, I found out that changing `${__dirname}/${folderName}/*.svg` to `${folderName}/*.svg` would fix the issue. 

To be honest, I don't quite understand why it is only working with relative one and not the relative one. But I have also tested on my other PC (Also Windows 11 with Node 18) and it seemed to working, so I made the pull request.

**Comment by replete** [comment]
Aha, I have reproduced this error in Windows.

If I do the npm install on MacOS, run that codebase from Windows. It works as-is.
If I run `npm install` from windows, the error you described is repeated. This is how it slipped through the cracks for me.

I have tested this PR in this scenario, and it does solve the problem ... though I'm not exactly sure what it is.

Screenshot 2024-06-09 at 17 05 04

Thumbs up from me

**Comment by replete** [comment]
@ArthurFGrillo Thanks for your contribution. I merged it after testing on Windows and MacOS.

I'd love to see how your custom icon set turned out.

Cheers, Phil

**Pull request merged**
